# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app
# Skip downloading Chromium since we connect to remote browser
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# Copy all files and install dependencies
COPY . .
RUN npm ci

# Build TypeScript
# npm ci triggers prepare build, but ensure build
RUN npm run build

# Run the MCP server
CMD ["node", "dist/index.js"]
